### ISSUE TITLE
The save-revision script could log a link to a commit that it's made

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#127]
Right now it doesn't log anything so you don't know if it worked and you can't go straight to that commit. So something like this would be nice:

> Successfully saved the revision under https://github.com/ckeditor/ckeditor5/commit/fc516a

**Comment by pomek** [comment]
What do you think about a message like this?

```js
const commitMessage = `https://github.com/${ process.env.TRAVIS_REPO_SLUG }/commit/${ process.env.TRAVIS_COMMIT }`;
```

I guess we don't need an information "Updated hashes." because this branch will have only commits which update the hashes.

**Comment by Reinmar** [comment]
Yep, I think it makes sense. It came to my mind too that we could point to the exact commit which updated the revision.

However, I'd extend it to something like:

`Revision: ...the url...`
