### ISSUE TITLE
Speed up package installation by using shrinkwrap or caching?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev#13]
Moved from: https://github.com/ckeditor/ckeditor5-dev-env/issues/20

**Comment by pomek** [comment]
@Reinmar, is this ticket still valid?

**Comment by Reinmar** [comment]
I don't think so.

**Comment by Reinmar** [comment]
We introduced a lot of tools in the meantime which sped up the installation process – e.g. Lerna and mgit2.
