### ISSUE TITLE
[ENV] Transifex logs shouldn't be visible during `npm test`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev#134]
As in title, when I'm calling the `npm test` command, I would see the tests results. 

At this moment, tests results are mixed with transifex tasks logs:

![image](https://cloud.githubusercontent.com/assets/2270764/24042662/4292b2e4-0b13-11e7-9ab6-2076c2fd5a6f.png)

**Comment by ma2ciek** [comment]
Thanks for reporting the issue. Missed it.

**Comment by pomek** [comment]
I noticed one more thing:

![image](https://cloud.githubusercontent.com/assets/2270764/24094480/2c583ea2-0d59-11e7-9416-027fd7f2df7e.png)

I edited file `./packages/ckeditor5-dev-env/tests/index.js`

```diff
-describe( 'dev-env/index', () => {
+describe.only( 'dev-env/index', () => {
```

and executed `npm t`.

**Comment by pomek** [comment]
It appears in various places :D 

![image](https://cloud.githubusercontent.com/assets/2270764/24445070/010e8dc0-1469-11e7-8340-3dcdcf21666b.png)

**Comment by ma2ciek** [comment]
Yes. So the engine must using some async functions to test the number of listeners.
