### ISSUE TITLE
Closed tickets should not be hoisted

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#161]
I'd like this merge commit: 
![image](https://cloud.githubusercontent.com/assets/156149/24875155/762e32f0-1e27-11e7-8174-4b7684f80f4f.png)

To stay formatted like it is and not have the tickets moved to the first paragraph like you can see here:

https://github.com/ckeditor/ckeditor5-list/releases/tag/v0.6.0

The combined list of "closes #1 #2 #3" is just ungrammatically and inconsequently formatted. Also, the same thing doesn't happen when "Closes #1. Closes #2" are listed in the first line of the merge commit.

**Comment by Reinmar** [comment]
E.g. here it didn't happen: https://github.com/ckeditor/ckeditor5-heading/releases/tag/v0.9.0

**Comment by pomek** [comment]
We can turn off the hoisting by clearing [`options.referenceActions`](https://github.com/conventional-changelog-archived-repos/conventional-commits-parser#referenceactions) array in [`parser-options`](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-env/lib/release-tools/changelog/parser-options.js).

After that, we will be able to simplify the [`transformCommit()`](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-env/lib/release-tools/changelog/writer-options.js) function:
- remove an option `references` from `commit` parameter,
- remove rendering references in [commit template](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-env/lib/release-tools/changelog/templates/commit.hbs#L26-L59).
