### ISSUE TITLE
Webpack plugin should be able to parse and translate other files as well

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-dev#167]
For now webpack plugin is able to translate the `ckeditor-*/**` files only. It would be nice if it could translate other files, e.g. some custom 3rd party plugins as for sure there will be such a need.

**Comment by Reinmar** [comment]
It could be configurable with a regexp used to match package names or directories (better the former).

**Comment by ma2ciek** [comment]
And the directory structure should be considered as well.
 - path to the `ckeditor5-core`'s translations
 - path to the `po` files

For me both of them should be configurable as well.

**Comment by Reinmar** [comment]
> path to the ckeditor5-core's translations

Why this?

> path to the po files

Yy... but the po files are in their standard location.

We should not make this tool generic for all projects. It's CKEditor tool. If any other project would like to use it we may try to make parts of it reusable, but not the entire plugin. The plugin is CKEditor's plugin.
