### ISSUE TITLE
Add "internal" option to the version picker

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#184]
When picking a version suggested by the changelog task, sometimes you'd like to say that all changelog entries should be ignored (because they are relevant to other subpackages, not this one) and that this should be a patch release for an internal change (with that nice "Internal changes only (updated dependencies, documentation, etc.)." text).

So, this is like picking the patch bump option, but with discarding all the changelog entries.

**Comment by Reinmar** [comment]
This is important because without these empty entries in the changelog the changelog task is bothering me with some old changes in packages which had releases in the meantime:

![image](https://cloud.githubusercontent.com/assets/156149/26122658/86413cd8-3a78-11e7-8730-e5f2fedb4d9a.png)

This package was released after I did those changes but it has no changelog entry (because the only option now was to totally skip its generation).

**Comment by Reinmar** [comment]
There's also this odd issue:

![image](https://cloud.githubusercontent.com/assets/156149/26122769/efc20a70-3a78-11e7-94f7-fd8aa73110fc.png)

For some reason the tool doesn't see the last change (listed in the right pane) ;|

**Comment by Reinmar** [comment]
I can reproduce the second issue for the second time now. I changed a file (this time – `.eslintrc.js`) in this specific package (eslint-config-ckeditor5) and the tool propose to skip this package anyway.

**Comment by pomek** [comment]
I guess we need to figure out another solution for gathering changed files based on commit SHA-1.

Note: #173 (comment)

**Comment by pomek** [comment]
Bug related to invalid bumping a version was reported https://github.com/ckeditor/ckeditor5-dev/issues/207.
