### ISSUE TITLE
JSDoc plugins: link validation does not work

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#228]
This is definitely a missed error (because as a module item it should be `.` not `~` there):

![image](https://user-images.githubusercontent.com/156149/27031301-1045e9c2-4f70-11e7-8c13-53b734fbac93.png)

~~And about this I'm unsure:~~

![image](https://user-images.githubusercontent.com/156149/27031306-1429cf2c-4f70-11e7-8f88-07d7540501e2.png)

~~The references are good so perhaps it's just Umberto failing to render them.~~ (see https://github.com/ckeditor/ckeditor5-dev/issues/228#issuecomment-308042049)

**Comment by Reinmar** [comment]
cc @m-turek

**Comment by m-turek** [comment]
About the second issue: Umberto doesn't support shorthands like `{@link ~Classname#methodName}`, it expects a full reference like: `module:x/y/z~Z`. I wasn't aware of a shorthand format. So I'd have to add support for it to make it work.

**Comment by Reinmar** [comment]
I thought so. Could you report #228 and #229 for Umberto so we can track these issues (both of them can be handled separately from issues in this repo)?

**Comment by Mgsy** [comment]
It's fixed.
