### ISSUE TITLE
Comma dangle

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-dev#234]
Can we add `"comma-dangle": [ "error", "never" ]` to our eslint preset?

AFAIK we follow this approach in all repos.

WDYT @Reinmar?

**Comment by Reinmar** [comment]
I didn't enable it on purpose – I neither like dangling commas everywhere nor I wanted to prohibit leaving any commas.

However, if you guys feel that it'd be good to have a strict rule here, we may consider introducing it.

**Comment by mlewand** [comment]
Good news, it happened just couple days ago, see #597 :tada:
