### ISSUE TITLE
`sudo: required` is deprecated on Travis

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-dev#238]
Check the note on https://travis-ci.org/

> This job ran on our Trusty, sudo: required environment which was updated on Wednesday, June 21st. Read all about it on our blog and take note that you can add group: deprecated-2017Q2 in your .travis.yml file to use the previous version.

With the link to https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

**Comment by Reinmar** [comment]
>  It’s possible that your build won’t succeed right away on these new images. If your builds are running on the sudo enabled environment and need to revert to the previous generation of images, you can add the following YAML snippet in your .travis.yml file:

What does it mean for us? Can we use the new images and still have Google Chrome updated (I believe that this is why we use the sudo mode).

**Comment by Reinmar** [comment]
@pomek What can we do here?

**Comment by pomek** [comment]
Works fine without sudo (https://travis-ci.org/ckeditor/ckeditor5-autoformat/builds/569328355, https://github.com/ckeditor/ckeditor5-autoformat/commit/ed9d075f56ef6dbf3fb1e5d78d963a2d0343c25d).

**Comment by pomek** [comment]
Recently we changed a lot in our CI (https://github.com/ckeditor/ckeditor5/issues/2041). I guess our knowledge about Travis is up-to-date and we can close this ticket.
