### ISSUE TITLE
Use Headless Chrome for tests

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#239]
`gulp test` should use Headless Chrome by default.

There's a guide how to integrate it with Karma and Travis: https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

What interests me is:

* how's Headless Chrome installed? Is it part of Chrome's standard installation? Is it always in the same version?
* will running tests with it be faster?
* will all tests pass?

**Comment by oskarwrobel** [comment]
I was trying to use Headless Chrome for CKE5 tests a few days ago.

> - will running tests with it be faster?

Nope.

> - will all tests pass?

Yes.

**Comment by pomek** [comment]
At this moment we're able to use Headless Chrome by passing the `ChromeHeadless` value to the `--browsers` option:

```
gulp test --files=ui --browsers=ChromeHeadless
```

Thoughts the same like @oskarwrobel.

**Comment by Reinmar** [comment]
> will running tests with it be faster?
> Nope.

Is bootstrap time the same? From what @pomek  showed me there's a couple of sec difference, which may be especially pleasant in normal work when running just a few tests. Plus, perhaps lower memory usage, faster kill times, etc.

**Comment by pomek** [comment]
To clarify this:

> From what @pomek showed me there's a couple of sec difference

```
Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 6246 of 6252 (skipped 6) SUCCESS (1 min 4.789 secs / 18.27 secs)                         
HeadlessChrome 0.0.0 (Mac OS X 10.12.5): Executed 6246 of 6252 (skipped 6) SUCCESS (58.751 secs / 16.518 secs)
```

For `ckeditor5-ui` there is a just one-second difference. 

For `ckeditor5-autoformat` this difference is invisible:

![image](https://user-images.githubusercontent.com/2270764/27906559-571b2628-6244-11e7-93a3-eb3b1bdb52de.png)

![image](https://user-images.githubusercontent.com/2270764/27906585-74271bdc-6244-11e7-8296-ba64c6ba885c.png)

but I had to manually kill the Headless browser (`CTRL+C`).

**Comment by oskarwrobel** [comment]
I ran tests on both browsers several times and Headless was faster but the difference was very very little. One or two times Headless was even slower.

**Comment by oskarwrobel** [comment]
HeadlessChrome version `0.0.0` looks strange.

**Comment by Reinmar** [comment]
Hm... but this is tests execution time, isn't it? What about `time gulp test --files=autoformat`?
