### ISSUE TITLE
Tests stopped working on CI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#241]
See https://travis-ci.org/ckeditor/ckeditor5-dev/builds/252493421

Suddenly the log on CI became grey and tests which check some colours stopped working. All works fine locally.

This is either some new version of chalk or something. Or a new OS on CI. Or something really funky.

**Comment by Reinmar** [comment]
Why did you change tests? ;| What's changed?

**Comment by pomek** [comment]
I also tested it locally and it also works. 

Versions of `chalk` installed on both platforms (CI and my computer) are the same so I assumed the tests failed because of CI. I decided to change a little bit the assertions in tests and it works fine now.

**Comment by Reinmar** [comment]
But this is bad news that it's Travis cause the results of tests are harder to parse visually.

Could you look if anyone complained about it somewhere?

**Comment by pomek** [comment]
I didn't find any issue about it – https://github.com/travis-ci/travis-ci/issues – so maybe is it worth to report it?

**Comment by pomek** [comment]
Mocha tests also look strange – https://travis-ci.org/mochajs/mocha/jobs/103528682. 

Maybe I should check Mocha instead of Chalk…

**Comment by Reinmar** [comment]
I guess that Mocha's tests look grey cause of the Travis's change. Our tests failed not due to mocha but the fact that our Node code didn't print colors to the output. Which is, most likely, a problem with the env.
