### ISSUE TITLE
[tests] WARN [web-server]: 404: /foo.png

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev#247]
During the tests execution, sometimes Karma logs a warning `WARN [web-server]: 404: /foo`.

I believe we can do something with that.

It breaks the tests result composition 😥 

![image](https://user-images.githubusercontent.com/2270764/29109486-706d4f34-7ce3-11e7-9ba7-3482f60313cc.png)

**Comment by pomek** [comment]
One of the tests also requires `/foo` – `09 08 2017 09:14:00.434:WARN [web-server]: 404: /foo`.

**Comment by Reinmar** [comment]
That was already reported. We need add a file handler to Karma.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-dev/issues/139.
