### ISSUE TITLE
The changelog generator incorrectly turns @ckeditor/ckeditor5-foo into links to profiles

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#269]
It generated this:

```
* Introduced `AttributeCommand`. It was moved from `[@ckeditor](https://github.com/ckeditor)/ckeditor5-core/src/command/toggleattributecommand`. Closes [#47](https://github.com/ckeditor/ckeditor5-basic-styles/issues/47). ([0301d4a](https://github.com/ckeditor/ckeditor5-basic-styles/commit/0301d4a))
```

**Comment by Reinmar** [comment]
The same with such a text:

```
See ckeditor/ckeditor5#469.
```

**Comment by pomek** [comment]
I am checking how Github will render the thing below:

- organization and repository – ckeditor/ckeditor5-dev,
- my nick @pomek, 
- a full name of the engine package – @ckeditor/ckeditor5-engine, 
- a link to an issue in this repository (#269), 
- a link to PR in this repository (#273), 
- a link to PR in other repository cksource/mgit2#59,
- a link to an issue in other repository cksource/mgit2#58.
