### ISSUE TITLE
"Fixed" could be a synonym for "Fixes" which could be a synonym for "Fix"

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#271]
I see many merge commits which starts with "Fixed" instead of "Fixes". Let's handle them.

**Comment by pomek** [comment]
Sorry, I don't understand. We support `Fix` prefix. If commit starts with `Fixes` or `Fixed`, this commit is invalid.

**Comment by Reinmar** [comment]
So, thinking about good DX, we should also support Fixed and Fixes. As you can see, even I forgot which prefix is the right one.
