### ISSUE TITLE
The release tool should not mix committing with pushing and with publishing on GH and npm

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#272]
The process should look like this:

* first do all commits,
* then do all pushes,
* then publish all on npm,
* then publish all released on GH.

Right now, the tool mixes the first two steps together (commit+push) and it also mixes publishing which is unsafe because for 5 minutes (according to https://gist.github.com/Reinmar/8ae3db219d385df06ccb94cd6d17cfd6) we have an incomplete release on npm. This also breaks builds CI because pushes to the repo start builds which try to install packages which are not yet installed on npm. But it's hard to prevent that.

**Comment by pomek** [comment]
I had to change a little bit the order:

1. Do all commits (generate missing changelogs and update dependencies' versions),
2. Publish all packages on NPM (packages will have proper version for the next steps),
3. Do all pushes (it will trigger CI which will not crash because NPM contains proper versions),
4. Make the releases on GH.

**Comment by Reinmar** [comment]
I know that the order you proposed is better for running tests on CI because everything will be already in place when we push to GH. However, it's risky too because the repository may reject the tags or something and that would be bad if everything is already on npm.

So, I wanted to change the order to the one I proposed.

However, after having second thought I understood that you're right. Nothing relies on the repositories. Peoples' projects rely on npm. So that's the first thing to get right. We can always force push and clean GH after that if something broke (which is unlikely anyway).
