### ISSUE TITLE
Change the order of Features and Bug fixes in the changelog

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#293]
The expected order:

* Features,
* Bug fixes,
* Other,
* BREAKING CHANGES

I'm not sure about BCs, but I propose to have them last because they are extending the info above – usually, things mentioned in BCs only extend and underline what's mentioned earlier.

cc @wwalc

**Comment by wwalc** [comment]
Normally I'd be for BREAKING CHANGES on top. But considering there will be plenty of breaking API changes a more natural order seems to be from features to bug fixes like proposed above.
