### ISSUE TITLE
JSDoc: Optimize Doclet Validator plugin

### ISSUE THREAD

**Issue by m-turek** [ckeditor/ckeditor5-dev#306]
Doclet Validator plugin when run on the sources of CKEditor 5 currently takes up to 50 seconds. This is a lot when combined with other plugins and then running Umberto, so we need some optimizations.

**Comment by pomek** [comment]
Could you provide some description of this ticket? Would be nice to see why this is necessary. Even if now you know why it is required, in the future we can forget the reasons.

**Comment by m-turek** [comment]
Edited the first comment, thanks
