### ISSUE TITLE
Please, when the bbcode mode will support the table plugin?

### ISSUE THREAD

**Issue by 7starsone** [ckeditor/ckeditor5-dev#311]
Hello,
at the moment, I consider the lack of bbcode support for the table plugin as the only missing feature.

Can I know why, please?

Will it be there as soon as possible or can you address how to transpose, if possible?
Thanks

**Comment by Reinmar** [comment]
Hi! Do you mean CKEditor 4? CKEditor 5 has no bbcode support at all so it sounds like you're asking about CKEditor 4.

**Comment by 7starsone** [comment]
yes, CKEditor **4**.

> CKEditor 5 has no bbcode support at all
this because of the beta status ?

Thanks

**Comment by Reinmar** [comment]
No, support for BBCode wasn't planned. It's not a very popular feature in CKEditor 4 and we don't think that it actually makes sense to use BBCode for anything (except, perhaps, legacy systems).

In other words – it's not something that we'll work on, but such plugin is definitely possible to create, so if you'd like to work on that we can give you some hints how to start.

**Comment by Reinmar** [comment]
PS. CKEditor 4's bug tracker is here: https://github.com/ckeditor/ckeditor-dev/issues but I think that CKEditor 4 team will not want to work on adding support for tables to the bbcode plugin too.

**Comment by 7starsone** [comment]
> we can give you some hints how to start

yes, please, indeed I just need the bbcode support for the table plugin. I could even try to do it if some guidelines about it.

**Comment by Reinmar** [comment]
So, in CKEditor 5, similarly to CKEditor 4, you need to write your own [`DataProcessor`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_dataprocessor_dataprocessor-DataProcessor.html). Data processor is meant to transform editor's internal view to the expected output format and vice versa.

We have two data processors so far:

* [`HtmlDataProcessor`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_dataprocessor_htmldataprocessor-HtmlDataProcessor.html) which simply handle outputting and inputting HTML strings.
* [`GFMDataProcessor`](https://docs.ckeditor.com/ckeditor5/latest/api/module_markdown-gfm_gfmdataprocessor-GFMDataProcessor.html) which inputs/outputs Markdown string.

You can find the code of the latter one here: https://github.com/ckeditor/ckeditor5-markdown-gfm/blob/master/src/gfmdataprocessor.js. As you can see, there are just two method to implement – `toView()` (input) and `toData()` (output). 

Here you can also find how to set editor's data processor: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/markdown.html
