### ISSUE TITLE
Should CKEditorWebpackPlugin build lang files to lang/? 

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#330]
Since we renamed lang to language across the code base perhaps the `CKEditorWebpackPlugin` should build its output to `languages/` or `language/` or sth else?

**Comment by ma2ciek** [comment]
I've resaerched, that [Angular](https://angular.io/guide/i18n), [Moment.js](https://github.com/moment/moment/tree/develop/locale), [date-fns](https://github.com/date-fns/date-fns/tree/master/src/locale) and some tutorials to other libs usually store translations in the `locale` or `locales` directory.

**Comment by Reinmar** [comment]
I'm not sure yet. I could even go with `locale` since we even have such class (and it accepts language as its param), but at the same time, the name of the config option should rather match the name of the directory...

**Comment by Reinmar** [comment]
I DUPed this ticket myself in https://github.com/ckeditor/ckeditor5-dev/issues/354. Let's move the entire discussion there.
