### ISSUE TITLE
Tests on Travis fails due to memory consumption

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#332]
ckeditor5-engine's tests are so heavy now that they consume all the memory. We need to use `--max_old_space_size=4096` for them.

**Comment by Reinmar** [comment]
It turns out that adding  `--max_old_space_size=4096` only in `package.json` works only when doing `npm run *` from that specific package. In other cases, packages' scripts are installed via copy&paste so this information is lost. So it needs to be used directly in the executable one's calling.

**Comment by jodator** [comment]
also happened here: https://github.com/ckeditor/ckeditor5-dev/issues/320 ;)

**Comment by Reinmar** [comment]
DUP of #320.
