### ISSUE TITLE
npm install webpack-dev is not working.

### ISSUE THREAD

**Issue by teoCasasbuenas** [ckeditor/ckeditor5-dev#336]
Can't install '@ckeditor/ckeditor5-dev-webpack-plugin'. Keeps telling me this:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/ma2ciek/escodegen.git
npm ERR! 
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Operation timed out
npm ERR! github.com[1: 192.30.253.113]: errno=Operation timed out
npm ERR! 
npm ERR! 
npm ERR! exited with error code: 128

Please help, I am looking forward to use CKEditor5 in my angular2 app.

**Comment by Reinmar** [comment]
Apparently, it's GitHub having's issues. Did you try again after a while?

**Comment by teoCasasbuenas** [comment]
Yup, still not working, the error increased.
[npm-debug.log](https://github.com/ckeditor/ckeditor5-dev/files/1536785/npm-debug.log)

**Comment by ma2ciek** [comment]
That's weird. Maybe it's because of the NPM@3, you're using(?) I'm using `NPM@4.6.1` and `Node@6.10.3` and can't reproduce it.

I remember, that we made a fork to be able to update `escodegen`'s dependencies to support ES6 syntax. I've checked the current dependencies of `escodegen` and we can roll back to the original repo.

I'll write a ticket for it, maybe it'll solve your issue too.

**Comment by teoCasasbuenas** [comment]
Thank you @ma2ciek my the NPM version is 3.10.10, Node@8.9.2. Will upgrade NPM and check if doing so resolve my issue. I also found that in the classic editor i haven't been able to use the `e.on('event', ()=>{});` My workaround is to use `e.document.on('event', ()=>{})` Why is it needed to bind it to the e.document? Shouldn't it be specified at the documentation?

**Comment by ma2ciek** [comment]
Thanks for reporting the above error @teoCasasbuenas. Could you report it to the https://github.com/ckeditor/ckeditor5/issues with the steps needed to reproduce it?

**Comment by Reinmar** [comment]
To make it clear – let's keep the issue with installing `@ckeditor/ckeditor5-dev-webpack-plugin` here and move only the other one (the one with listening to events) to https://github.com/ckeditor/ckeditor5/issues.

BTW, did upgrading to npm 4.x+ help?

**Comment by teoCasasbuenas** [comment]
No @Reinmar  upgrading didn't solve my problem. 
My development environment: 
- MacBook pro OS High Sierra. 
- Node@8.9.2
- NPM@4.6.1

I have two scenarios, neither works. First I have this Angular 4 project, and i was looking forward to upgrade my CKEditor, so I was trying to make my own build, so I tried to follow [the docs guide](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#Scenario-2-Building-from-source), but the package installation failed as I pointed before.

The second stage is a new scratch project, no framework involved, but the outcome is the same.

I'm attaching the debug log. 

Thanks a lot for you cooperation.

Complete log: [2017-12-11T13_26_22_918Z-debug.log](https://github.com/ckeditor/ckeditor5-dev/files/1547935/2017-12-11T13_26_22_918Z-debug.log)

Following your advise i will create an issue with the listening events.

**Comment by Reinmar** [comment]
I've got the same npm version and Node 6.9.1 and it WFM:

```
p@m /workspace/stuff/x> npm i @ckeditor/ckeditor5-dev-webpack-plugin
npm WARN checkPermissions Missing write access to /workspace/node_modules
/workspace
└─┬ @ckeditor/ckeditor5-dev-webpack-plugin@3.0.3
  └─┬ @ckeditor/ckeditor5-dev-utils@7.0.2
    ├── acorn@5.2.1
    ├─┬ del@3.0.0
    │ ├─┬ globby@6.1.0
    │ │ ├─┬ array-union@1.0.2
    │ │ │ └── array-uniq@1.0.3
    │ │ ├── glob@7.1.2  deduped
    │ │ ├── object-assign@4.1.1
    │ │ ├── pify@2.3.0
    │ │ └─┬ pinkie-promise@2.0.1
    │ │   └── pinkie@2.0.4
    │ ├── is-path-cwd@1.0.0
    │ ├─┬ is-path-in-cwd@1.0.0
    │ │ └─┬ is-path-inside@1.0.1
    │ │   └── path-is-inside@1.0.2
    │ ├── p-map@1.2.0
    │ ├── pify@3.0.0
    │ └─┬ rimraf@2.6.2
    │   └── glob@7.1.2  deduped
    ├─┬ escodegen@1.8.1  (git://github.com/ma2ciek/escodegen.git#103e5907aa3cc0bff90e58be8fd5e997da40f3ae)
    │ ├── esprima@2.7.3
    │ ├── estraverse@4.2.0
    │ ├── esutils@2.0.2
    │ ├─┬ optionator@0.8.2
    │ │ ├── deep-is@0.1.3
    │ │ ├── fast-levenshtein@2.0.6
    │ │ ├─┬ levn@0.3.0
    │ │ │ ├── prelude-ls@1.1.2  deduped
    │ │ │ └── type-check@0.3.2  deduped
    │ │ ├── prelude-ls@1.1.2
    │ │ ├─┬ type-check@0.3.2
    │ │ │ └── prelude-ls@1.1.2  deduped
    │ │ └── wordwrap@1.0.0
    │ └─┬ source-map@0.2.0
    │   └── amdefine@1.0.1
    ├─┬ fs-extra@4.0.3
    │ ├── graceful-fs@4.1.11
    │ ├─┬ jsonfile@4.0.0
    │ │ └── graceful-fs@4.1.11  deduped
    │ └── universalify@0.1.1
    ├── javascript-stringify@1.6.0
    ├── pofile@1.0.10
    ├─┬ postcss-import@11.0.0
    │ ├─┬ postcss@6.0.14
    │ │ ├─┬ chalk@2.3.0
    │ │ │ ├─┬ ansi-styles@3.2.0
    │ │ │ │ └─┬ color-convert@1.9.1
    │ │ │ │   └── color-name@1.1.3
    │ │ │ ├── escape-string-regexp@1.0.5
    │ │ │ └── supports-color@4.5.0  deduped
    │ │ ├── source-map@0.6.1
    │ │ └─┬ supports-color@4.5.0
    │ │   └── has-flag@2.0.0
    │ ├── postcss-value-parser@3.3.0
    │ ├─┬ read-cache@1.0.0
    │ │ └── pify@2.3.0
    │ └─┬ resolve@1.5.0
    │   └── path-parse@1.0.5
    ├─┬ postcss-mixins@6.2.0
    │ ├── globby@6.1.0  deduped
    │ ├── postcss@6.0.14  deduped
    │ ├─┬ postcss-js@1.0.1
    │ │ ├── camelcase-css@1.0.1
    │ │ └── postcss@6.0.14  deduped
    │ ├─┬ postcss-simple-vars@4.1.0
    │ │ └── postcss@6.0.14  deduped
    │ └─┬ sugarss@1.0.1
    │   └── postcss@6.0.14  deduped
    ├─┬ postcss-nesting@4.2.1
    │ └── postcss@6.0.14  deduped
    ├─┬ shelljs@0.7.8
    │ ├─┬ glob@7.1.2
    │ │ ├── fs.realpath@1.0.0
    │ │ ├─┬ inflight@1.0.6
    │ │ │ ├── once@1.4.0  deduped
    │ │ │ └── wrappy@1.0.2
    │ │ ├── inherits@2.0.3
    │ │ ├─┬ minimatch@3.0.4
    │ │ │ └─┬ brace-expansion@1.1.8
    │ │ │   ├── balanced-match@1.0.0
    │ │ │   └── concat-map@0.0.1
    │ │ ├─┬ once@1.4.0
    │ │ │ └── wrappy@1.0.2  deduped
    │ │ └── path-is-absolute@1.0.1
    │ ├── interpret@1.1.0
    │ └─┬ rechoir@0.6.2
    │   └── resolve@1.5.0  deduped
    └─┬ through2@2.0.3
      ├─┬ readable-stream@2.3.3
      │ ├── core-util-is@1.0.2
      │ ├── inherits@2.0.3  deduped
      │ ├── isarray@1.0.0
      │ ├── process-nextick-args@1.0.7
      │ ├── safe-buffer@5.1.1
      │ ├─┬ string_decoder@1.0.3
      │ │ └── safe-buffer@5.1.1  deduped
      │ └── util-deprecate@1.0.2
      └── xtend@4.0.1
```

But in your log there's this:


```
642 silly fetchPackageMetaData  error for escodegen@git://github.com/ma2ciek/escodegen.git { Error: Command failed: git clone --template=/Users/teocasasbuenas/.npm/_git-remotes/_templates --mirror git://github.com/ma2ciek/escodegen.git /Users/teocasasbuenas/.npm/_git-remotes/git-github-com-ma2ciek-escodegen-git-2a478501
642 silly fetchPackageMetaData Cloning into bare repository '/Users/teocasasbuenas/.npm/_git-remotes/git-github-com-ma2ciek-escodegen-git-2a478501'...
642 silly fetchPackageMetaData fatal: unable to connect to github.com:
642 silly fetchPackageMetaData github.com[0: 192.30.253.112]: errno=Operation timed out
642 silly fetchPackageMetaData github.com[1: 192.30.253.113]: errno=Operation timed out
642 silly fetchPackageMetaData
642 silly fetchPackageMetaData
```

Could you try to clone this repository manually? If you could manually execute this command:

```
git clone --template=/Users/teocasasbuenas/.npm/_git-remotes/_templates --mirror git://github.com/ma2ciek/escodegen.git /Users/teocasasbuenas/.npm/_git-remotes/git-github-com-ma2ciek-escodegen-git-2a478501
```

And also: 


```
git clone git://github.com/ma2ciek/escodegen.git
```

Just to make sure. If this command won't work then there's something wrong with your git/internet connection/no idea what.

**Comment by teoCasasbuenas** [comment]
Ok, finally i found that it was my internet provider that for some reason got that ip's blocked. 

Sorry about the time wasted.

**Comment by Reinmar** [comment]
No problem :) Glad we figured that out.
