### ISSUE TITLE
Are theme importer log's printed by default?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#339]
I mean this: 

![image](https://user-images.githubusercontent.com/156149/33840653-cffc2f6a-de95-11e7-9fad-8fdf5eaa21d6.png)

Or is it something that's enabled in our tests only?

cc @oleq

**Comment by oleq** [comment]
[Theme importer's logs are enabled for manual tests only](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-tests/lib/utils/manual-tests/getwebpackconfig.js#L58).

**Comment by Reinmar** [comment]
❤️
