### ISSUE TITLE
Switch CodeClimate to Coveralls

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev#348]
Because we don't use any feature which offers CodeClimate, let's switch it to Coveralls.

It's easier to set up for a new repository and adds a comment in every PR which contains a status of code coverage after merging the PR.

![image](https://user-images.githubusercontent.com/2270764/34253903-da6386d6-e649-11e7-9f17-54f96b61f0bd.png)

**Comment by oleq** [comment]
I just noticed that in [certain situations](https://github.com/ckeditor/ckeditor5-widget/pull/30) the markdown formatting is broken
![image](https://user-images.githubusercontent.com/1099479/34378581-db921e26-eaf6-11e7-97f1-0ec2cf66b09d.png)
Can we fix that?

**Comment by Reinmar** [comment]
We should report it to @coveralls.

**Comment by oleq** [comment]
@pomek, can you handle that?

**Comment by pomek** [comment]
It is broken because the latest commit on master does not have a coverage report.

An example of the comment if the latest commit on the master has the coverage report.

![image](https://user-images.githubusercontent.com/2270764/34599711-16cb8ff0-f1f4-11e7-8c03-e01f9fb48e38.png)

```
Coverage remained the same at 100.0% when pulling **a81391eb61d976dbd611df45b5ec4c0935100725 on t/1212** into **4e4f5c3a0947c0097f2bd75e3d9f16882681ccc6 on master**.
```

I'm not sure whether we or @coveralls can do anything with it. Reported here – https://github.com/lemurheavy/coveralls-public/issues/1053.

**Comment by pomek** [comment]
Or should we stop committing to master with the `[skip ci]` tag?
