### ISSUE TITLE
Build of manual tests works weird when name of project directory is other then ckeditor5

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-dev#351]
I wanted to create second workspace with CKE5 so I cloned the project to `ckeditor5-second` directory and then I run manual tests for the entire project and booooom:
```shell
~/P/c/ckeditor5-second (master|✔) $ npm run test:manual

> ckeditor5@1.0.0-alpha.2 test:manual /Users/oskarwrobel/Projects/cksource/ckeditor5-second
> node --max_old_space_size=4096 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test-manual.js

Removed directory '/Users/oskarwrobel/Projects/cksource/ckeditor5-second/build/.manual-tests'
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should not be empty.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
```

When I run tests for specified package I don't see the error anymore but still, something is wrong because log is very short (many files are missing) and tests don't work:
```shell
~/P/c/ckeditor5-second (master|✔) $ npm run test:manual -- --files upload

> ckeditor5@1.0.0-alpha.2 test:manual /Users/oskarwrobel/Projects/cksource/ckeditor5-second
> node --max_old_space_size=4096 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test-manual.js "--files" "upload"

Removed directory '/Users/oskarwrobel/Projects/cksource/ckeditor5-second/build/.manual-tests'
[Webpack] Starting scripts compilation...
Processing '/Users/oskarwrobel/Projects/cksource/ckeditor5-second/packages/ckeditor5-upload/tests/manual/imageplaceholder'...
Finished writing '/Users/oskarwrobel/Projects/cksource/ckeditor5-second/build/.manual-tests/ckeditor5-second/packages/ckeditor5-upload/tests/manual/imageplaceholder.html'
Processing '/Users/oskarwrobel/Projects/cksource/ckeditor5-second/packages/ckeditor5-upload/tests/manual/imageupload'...
Finished writing '/Users/oskarwrobel/Projects/cksource/ckeditor5-second/build/.manual-tests/ckeditor5-second/packages/ckeditor5-upload/tests/manual/imageupload.html'
[Webpack] Finished the compilation.
[Server] Server running at http://localhost:8125/
```

Removing `-` from directory name (`ckeditor5second`) helps because tests for specified packages work but still tests for entire project don't.

**Comment by pomek** [comment]
I describe steps required to fix that issue:

**/ckeditor5-dev/packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js**

https://github.com/ckeditor/ckeditor5-dev/blob/07ec4642e91119ac67d1cef3375b2c2a7e68dbdf/packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js#L18-L20

It fails because `ckeditor5-second` is matched instead of the real package. Because we want to work on the package name, we can skip everything before. 

```js
module.exports = function getRelativeFilePath( filePath ) {
	const chunks = filePath.split( 'ckeditor5-' );

	return 'ckeditor5-' + chunks[ chunks.length - 1 ];
};
```

**/ckeditor5-dev/packages/ckeditor5-dev-utils/lib/styles/themeimporter.js**

https://github.com/ckeditor/ckeditor5-dev/blob/07ec4642e91119ac67d1cef3375b2c2a7e68dbdf/packages/ckeditor5-dev-utils/lib/styles/themeimporter.js#L191

As noticed @carltoncolter in #382 – we need to match the last `ckeditor5-` prefix instead of the first one. Adding `/g` flag to the RegExp resolves the issue.

```js
const match = inputFilePath.match( /ckeditor5-[^\\/]+/g );
```

**/ckeditor5-dev/packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js**

https://github.com/ckeditor/ckeditor5-dev/blob/07ec4642e91119ac67d1cef3375b2c2a7e68dbdf/packages/ckeditor5-dev-tests/lib/utils/manual-tests/createserver.js#L120-L121

We want to retrieve the relative path. We know both absolute paths: the dist directory where everything has been built and the particular file. We can remove the first one from the second one and everything will work. `ckeditor5-` checks aren't required.

```js
const relativeFilePath = file.replace( sourcePath + escapedPathSep, '' );
```

**Comment by pomek** [comment]
☝The solution above works if we define the `--files` parameters during `npm run test:manual`.

For running all the tests I need more time.

**Comment by pomek** [comment]
`npm run test:manual` without the `--files` is executed as `--files=/` which is transformed as:

https://github.com/ckeditor/ckeditor5-dev/blob/07ec4642e91119ac67d1cef3375b2c2a7e68dbdf/packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js#L12
https://github.com/ckeditor/ckeditor5-dev/blob/07ec4642e91119ac67d1cef3375b2c2a7e68dbdf/packages/ckeditor5-dev-tests/lib/utils/transformfileoptiontotestglob.js#L37-L40

In my case it is: `/Users/pomek/Projects/ckeditor/ckeditor5-copy/tests/**/manual/**/*.js`.

As we know, the base directory does not contain any test. If you want to run those tests, you need to specify files as `--files=**`. It will help.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5-dev/pull/382#issuecomment-374392112

> could we somehow remove this limitation regarding the directory name?

@Reinmar, answering on your question – we can remove the whole `ckeditor5-` checks but we will need to specify the full package name in the CLI (e.g. `npm t -- --files=ckeditor5-core`).

AFAIR we assumed that `ckeditor5-` prefix will be always defined only for package names. I don't remember exactly why it is required. Did we need the package name? In @oskarwrobel case, we have "package name pattern" as a base path. It breaks our assumptions and the script won't work correctly.

**Comment by Reinmar** [comment]
One more case came to my mind that we need to remember:

```
/Users/pomek/ckeditor5-workspace/ckeditor5/ckeditor5-copy/tests/**/manual/**/*.js.
```

E.g. @AnnaTomanek uses `ckeditor5-workspace/` directory to keep all CKEditor 5 related stuff.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5-build-classic/issues/41#issuecomment-374555661

**Comment by Reinmar** [comment]
This will be easier: 

```
diff --git a/packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js b/packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js
index 990d367..db66084 100644
--- a/packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js
+++ b/packages/ckeditor5-dev-tests/lib/utils/getrelativefilepath.js
@@ -16,5 +16,5 @@ const escapedPathSep = path.sep == '/' ? '/' : '\\\\';
 // In order to do that, everything up to `ckeditor-*/` is removed:
 // /work/space/ckeditor5-foo/tests/manual/foo.js -> ckeditor5-foo/tests/manual/foo.js
 module.exports = function getRelativeFilePath( filePath ) {
-    return filePath.replace( new RegExp( '^.+?' + escapedPathSep + 'ckeditor5-' ), 'ckeditor5-' );
+    return filePath.replace( new RegExp( '^.+' + escapedPathSep + 'ckeditor5-' ), 'ckeditor5-' );
 };
```

I'm not sure why we made that `^.+?` bit non-greedy. It makes sense that it's greedy.
