### ISSUE TITLE
Should we rename or lang/ directories to languages/?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#354]
Right now we have this:

```
(master 3a83efc) p@m /...ckeditor5/packages/ckeditor5-build-classic> tree build
build
├── ckeditor.js
├── ckeditor.js.map
└── lang
    ├── ast.js
    ├── bg.js
    ├── da.js
    ├── de.js
    ├── el.js
    ├── en-au.js
```

And:

```
(master 912570d M35) p@m /...ckeditor5/packages/ckeditor5-core> tree -L 2

...
├── docs
│   └── api
├── lang
│   ├── contexts.json
│   └── translations
├── src
...
├── tests
...
└── theme
    └── icons
```

While the configuration options that we have (for both the editor and for `CKEditor5WebpackPlugin` are after named "language").

This is kinda inconsistent and I've just made a mistake because of that. But... we also have `docs/` and `src/`, so if we'll suddenly rename `lang/` to `languages/` or `language/` it won't be good either.

What I also don't like is the two level of `lang/translations/` but it exposes `contexts.json` a bit more (the only file you manage manually there – the rest is automatically downloaded).

**Comment by Reinmar** [comment]
TBH, despite the inconsistency between `lang/` dir and `language` config option I don't see a better option out there. Maybe one – to rename the directory to `translations/`. The config option specifies editor's language, while the directory keeps translations. So perhaps they don't have to be named identically. 

WDYT?

**Comment by Reinmar** [comment]
What worries me the most now is the confusion for people who will be integrating the editor on their websites. That's the most important thing that I'd like to resolve here.

**Comment by wwalc** [comment]
> TBH, despite the inconsistency between lang/ dir and language config option I don't see a better option out there. Maybe one – to rename the directory to translations/.

Why not. Looks okay to me.

**Comment by Reinmar** [comment]
https://github.com/ckeditor/ckeditor5-dev/issues/330 was marked as a DUP.

**Comment by ma2ciek** [comment]
So, you want only to rename the `build/lang` to `build/translations` and leave the rest as it is for now? Am I right?

```
build
├── ckeditor.js
├── ckeditor.js.map
└── translations
    ├── ast.js
    ├── bg.js
    ├── da.js
```

> What I also don't like is the two level of lang/translations/ but it exposes contexts.json a bit more (the only file you manage manually there – the rest is automatically downloaded).

 IMO it's good to separate them.

**Comment by Reinmar** [comment]
> So, you want only to rename the build/lang to build/translations and leave the rest as it is for now? Am I right?

No. This ticket is also about all repositories where we have the `lang/` directory. But I don't know what to do with these :D I think that we have two options if we want to keep the `context.json` visible:

* Keep what we have now. There still will be `translations/` directory (just like in builds) but it won't be the outermost one.
* Move `translations/` out of `lang/` (to have it in the root of each package) and move `context.json` to the root as well but rename it to something like `translation-contexts.json`.

I'm not sure which option I like more. Perhaps the first one because if needed we can easily add more files inside `lang/` without bloating the root directory. But at the same time, it may not be about languages anymore but about locales (especially, if we'll add there more files).

**Comment by wwalc** [comment]
+1 for the second option with less folders. If we ever work on more sophisticated l10n topics and introduce even more files, then the additional top-level `lang` folder would be have a bad name for it anyway. But I doubt we'd be working on it, so translations seems like an intuitive name for developers.

**Comment by ma2ciek** [comment]
For now, we have 10 files in every package root level, so it would be the 11nth one... Both options have some pros and cons, but if we can have more 18n files, then I'd keep all these files in the `translations/` (or `locale/` ?)  directory.

**Comment by Reinmar** [comment]
OK, let's keep what we have now. At least we won't have to spend time on this. It's okayish that:

* in the source packages we use the name `lang/` because we also use the name `src/` (as opposed to `source/`),
* we have the `lang/translations/` directory, so there's match with what we have in builds.
