### ISSUE TITLE
[PostCSS] Watcher should observe dependencies of the theme files

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-dev#359]
## Intro

ATM, if a theme (e.g. Lark) imports some other CSS file (e.g. `_colors.css`), the dependency chain is as follows:

```
ckeditor5-foo/theme/foo.css 
   -> ckeditor5-theme-lark/theme/ckeditor5-foo/foo.css 
      -> ckeditor5-theme-lark/theme/_colors.css
```

## Problem

While the first level is [handled here](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-utils/lib/styles/themeimporter.js#L116-L119), the 2nd-level dependencies (`_colors.css`) are not observed by the watcher.

As a result, changing such files won't trigger rebuild and there's no way to change colors/fonts/whatever and see the results live in manual tests.

## What should we do?

We should do some research to figure out how to include such theme dependencies in the watcher and make the entire code-base dynamic.

**Comment by Reinmar** [comment]
I moved it to it15. It would be worth to fix it because it was a bit surprising.

BTW, if you wish to play with the theme live, dev tools display the colors and other variables at the end of the styles list:

![image](https://user-images.githubusercontent.com/156149/35800704-03bc31ec-0a6a-11e8-9b35-de4992b9aa09.png)

**Comment by oleq** [comment]
Yeah, I find it more and more cumbersome every day. Especially when changes are to the colors/fonts/spacings and the restart of the manual test server is needed.

**Comment by pomek** [comment]
I pushed a branch [t/359](https://github.com/ckeditor/ckeditor5-dev/compare/t/359) which probably fix that issue.

Could you guys confirm that the issue is no more a thing?

**Comment by oleq** [comment]
@pomek Checked and LGTM; PR it, please.
