### ISSUE TITLE
[JSDoc] Doclet validator does not detect '{@link @link ...}'

### ISSUE THREAD

**Issue by m-turek** [ckeditor/ckeditor5-dev#365]
Here is an issue, which doclet validator didnt't detect:

https://github.com/ckeditor/ckeditor5-ui/blob/master/src/view.js#L187

**Comment by ma2ciek** [comment]
`{module:engine/...}` too and that's also a common mistake.

**Comment by ma2ciek** [comment]
Actually, errors of this type ( `{module:engine/...}` ) are hard to detect as `@type`, `@see` and other keywords prefix reference wrapped in curly brackets.

**Comment by ma2ciek** [comment]
I improved `@link` tag detection which was a little bit buggy (e.g. didn't catch links that have `'` in their descriptions)  and linked ~1000 more references.
But they'll some new incorrect reference detections too 😢

New unhandled links:
<img width="317" alt="screen shot 2018-02-13 at 18 36 45" src="https://user-images.githubusercontent.com/2768047/36164880-08771b2c-10ee-11e8-9f9c-aac4cbe07e84.png">

New errors after improved handing (incorrect references):
<img width="235" alt="screen shot 2018-02-13 at 18 44 05" src="https://user-images.githubusercontent.com/2768047/36164890-1013193a-10ee-11e8-8d0b-35488b63c191.png">

**Comment by Reinmar** [comment]
Are you sure the validation works ok? 1000 errors sound crazy.

**Comment by ma2ciek** [comment]
I meant ( 1002 - 46 ) new links and 46 errors after that change. And there will be in fact ~10 errors as many of these 46 errors are duplicated because of the inheritance.

**Comment by ma2ciek** [comment]
All API docs fixes are on these branches: https://github.com/ckeditor/ckeditor5-dev/pull/366#issuecomment-365601671
