### ISSUE TITLE
Webpack plugin should be refactored

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-dev#4]
Logic should be moved to `resolveimportpath.js` to enable using this stuff in Rollup plugin.

**Comment by ma2ciek** [comment]
I'm not sure whether this ticket is up to date after we have switched to the multi-repo package.

**Comment by Reinmar** [comment]
It's invalid ATM because we don't support overriding path resolution. The Webpack plugin supports only translations.
