### ISSUE TITLE
Travis builds fail too often

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev#405]
Because of the timeout. I would like to increase the timeout from 10s to 15s for the last time. 

If it won't help, we would need to rewrite few tests.

**Comment by pomek** [comment]
Of course, we already did it in the past:

- https://github.com/ckeditor/ckeditor5-dev/issues/205
- https://github.com/ckeditor/ckeditor5-dev/issues/232

**Comment by Reinmar** [comment]
Closed with https://github.com/ckeditor/ckeditor5-dev/pull/406.
