### ISSUE TITLE
Releasing ckeditor5 together with other packages

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#427]
So far we've been releasing `@ckeditor/ckeditor5-*` first and then, if we had confirmation from CI that it went well, we've been publishing `ckeditor5`.

However, `ckeditor5` became a dependency of `@ckeditor/ckeditor5-utils`, which mean that we have to bump up their versions together. Or, in fact, we could even release `ckeditor5` first (it has no dependencies itself).

Anyway, we need to review our previous release process and make sure that between calling `npm release:dependencies` and `npm release` there are no manual steps so this can be done one after another to finally become a single step.

**Comment by pomek** [comment]
> npm release there are no manual steps so this can be done one after another to finally become a single step.

Someone has to update the README (paste a link to the latest release). That's the one (manual) step between those scripts.

**Comment by Reinmar** [comment]
In fact... we'll always go with the socials on the next day after tagging the releases. So, we don't have a working link to the blog post at this stage. However, we can have release notes, so for that we should prompt immediately.

**Comment by pomek** [comment]
After step 6. the changelog task will continue. I forgot to add it.

**Comment by Reinmar** [comment]
Cool! Looks great.

I'm only unsure about this markdown formatter. It hid the backticks around `npm version`, `npm pack`, etc. I'd like to see all the characters I typed.

**Comment by Reinmar** [comment]
So something like code highlighting would be awesome. But markdown to terminal converter not really. That may make it harder to validate some things.

**Comment by Reinmar** [comment]
We talked with @pomek that we don't need to prompt for anything because those changes can be done in the changelogs/readmes between `npm run changelog` and `npm run release`. The release script could only ask whether it was done (it can even look whether there's something between `## X.X.X` and `## Dependencies`).

Besides, we should redesign the internals of this script to better handle the fact that releasing `ckeditor5` is just an integral part of releasing all other packages. It needs to be done slightly differently, but it's part of this process.

**Comment by Reinmar** [comment]
We learnt today the hard way that `ckeditor5/package.json` needs to be updated before `npm version` is called in builds because builds read the version of `ckeditor5` from its `package.json`.

So we need to sort packages on which we execute `npm version` in the right order (`ckeditor5` can be first).
