### ISSUE TITLE
Switch to lerna+yarn

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#466]
We use lerna+npm, but yarn better supports lerna (see e.g. https://stackoverflow.com/questions/52181762/are-there-any-advantages-to-using-lerna-with-yarn-workspaces). The only problem I can see is with releasing packages – I'm not sure how well yarn handles this.

**Comment by pomek** [comment]
`ckeditor5-dev` still uses `lerna@3`.

**Comment by pomek** [comment]
After a few months, even if I wrote anything here… I don't know what is the ticket about.

**Comment by Reinmar** [comment]
About upgrading to lerna@3+ and using `npmClient: "yarn"` in `lerna.json` and checking that all works fine (including CI, releasing, etc.).

See https://github.com/lerna/lerna#lernajson

**Comment by pomek** [comment]
We are using Lerna 3 long time – https://github.com/ckeditor/ckeditor5-dev/commit/a6c89fafd285eb9d09b47e842e671954adb1abc5
