### ISSUE TITLE
Manual tests not watching .html and .md files

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-dev#52]
If I remember correctly this worked before - one could change .html or .md file and watcher updated manual tests.

**Comment by pomek** [comment]
In the previous version of dev-tests, we had something like this - https://github.com/ckeditor/ckeditor5-dev-tests/blob/master/lib/tasks.js#L183-L206.

**Comment by Reinmar** [comment]
Yes, we lost the feature upon rewriting it to the new project structure. Should be fairly easy to bring back.
