### ISSUE TITLE
The async keyword should be followed by a single space

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-dev#521]
The correct code for the async arrow function with the current `eslint-config-ckeditor5` rules looks like this:

```js
it( 'should display header message', async() => {} );
```

While the proper code style IMO should look like this:

```js
it( 'should display header message', async () => {} );
```

Unfortunately, it's a BC for anybody using our preset and the `async/await` syntax.

cc @jodator @Reinmar 

Ref https://eslint.org/docs/rules/space-before-function-paren.

**Comment by jodator** [comment]
I'm fine with breaking change if it will make code style OK.

Also should be tested for all variants:

```js
async () => {}
async function() {}
// etc
```

**Comment by Reinmar** [comment]
If the change will apply to async arrow functions only, then I'm ok as well.

**Comment by jodator** [comment]
I was checking the PR and I have a question: Where is this used? (sorry for not checking it earlier).

Right now we have a definition: 

```js
module.exports = {
	extends: 'eslint:recommended',
	parserOptions: {
		ecmaVersion: 6,
		sourceType: 'module'
	},
	// rest...
};
```

and the ESLint just breaks on `async` keyword. Which was defined [in ES2017 (8)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Specifications) while we're on ES2015 (6). So while we're adding the `space-before-function-param` support for `async` it will not work due to lower ECMA version.

**Comment by jodator** [comment]
We probably need to upgrade the ecmaVersion to at least `9` as we're using 7-9 features already. cc @Reinmar

**Comment by ma2ciek** [comment]
We use it outside of the ckeditor5 repository, e.g. in CF with the higher ecmaVersion option set. But yeah, upgrading the default `ecmaVersion` prop does make sense too.

**Comment by jodator** [comment]
So either this should go to overridden config or we should update it here already.

I'm for the latter to set it to '2018` (or `9`).

**Comment by jodator** [comment]
@Reinmar & @mlewand: quick summary of features used:

- [ES 2018](https://flaviocopes.com/es2018/):
    - RegExp enhancements (not linted, feature detection is used)
- [ES 2017](https://flaviocopes.com/es2017/):
    - `Object.values()` (my bad - tables)
    - `Object.entries()` (tables, remove format)
- [ES 2016](https://flaviocopes.com/es2016/):
    - `Array.includes()` (basically everywhere)

So minimum update is 2016, but updating to 2018 shouldn't introduce any side effects.

My vote is to bump this to to `2018` & close @ma2ciek PR.

**Comment by Reinmar** [comment]
👍
