### ISSUE TITLE
Manual test file query for running tests only from the main repo doesn't work on Windows

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-dev#558]
After #557 when I run `yarn run manual -f /` on Windows desktop I get following error:

```
Removed directory 'X:\dev\ckeditor5\ckeditor5\build\.manual-tests'
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be an non-empty object.
   -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When running `yarn run manual` manual tests are working just fine (also manual tests from root repo are served/listed correctly).

**Comment by pomek** [comment]
There is some ugly bug in Git Bash. It resolves `/` as an absolute path to an executable file. 

I pushed a temporary fix for the issue in https://github.com/ckeditor/ckeditor5-dev/commit/f929c80fc9f0098e2a3beb7fc1dd70fece420d83. Unfortunately, this fix works only for me. Most probably we need more data to take into consideration.

We could debug it a little deeper by analyzing `process.env` object on different machines. Another solution could be introducing a CLI parameter (e.g. `yarn run manual -f core --include-root`). 

The entire script works fine (`yarn run manual` does not throw). The problem occurs when we use `/` as a value in CLI.

As a workaround, I recommend using `cmd` for running `yarn run manual -f /`. Default Windows terminal works fine.

**Comment by pomek** [comment]
I added two new parameters for manual tests.

- #### `--include-root`
    Attach the main repository to compiled files. 
    `yarn run manual -f core --include-root` is equal to `yarn run manual -f core,/`
- #### `only-root`
    Compile manual tests from the main repository only.
    `yarn run manual --only-root` is equal to `yarn run manual -f /`

The fix is available on the [`t/558`](https://github.com/ckeditor/ckeditor5-dev/compare/t/558) branch.
