### ISSUE TITLE
Manual tests page for main repo leaks full path

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-dev#561]
![Selection_034a](https://user-images.githubusercontent.com/247363/65316265-e6ca2f00-db99-11e9-8172-b67ed14946ac.png)

I've run:
```
yarn manual --files=table,core,/
```

from
```
/home/user/projects/cksource/ckeditor5/git/ckeditor5/
```

I think that the culprit is the fact that I have linked

```
/home/user/projects
```
to
```
/mnt/uuid-of-the-disk/projects
```

**Comment by jodator** [comment]
Side note: we could drop the `manual` from the links as well.

**Comment by jodator** [comment]
Edit: I don't know what happened. But let's assume that I've worked from `/mnt/disk-uuid/projects` - still the full path should not be shown.

**Comment by jodator** [comment]
Also causes this: 
![Selection_001](https://user-images.githubusercontent.com/247363/65325857-49c6c080-dbb0-11e9-97bd-cf4e07716ae7.png)

**Comment by mlewand** [comment]
I don't see this issue anymore (tested both on Win10 and Ubuntu host). @pomek @Mgsy can one of you verify that it is no longer a thing and close this issue in such case?

**Comment by pomek** [comment]
I couldn't reproduce the issue so I cannot confirm anything. I guess we need a confirmation from @jodator.

**Comment by jodator** [comment]
WFM now.
