### ISSUE TITLE
Manual tests form main package are not loaded by default

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-dev#562]
If I run 
```
yarn manual
```
I'd expect that all manual tests are loaded (including those from the main package).

**Comment by pomek** [comment]
They are.

```
yarn manual
yarn run v1.16.0
$ node --max_old_space_size=4096 node_modules/@ckeditor/ckeditor5-dev-tests/bin/test-manual.js
Removed directory '/Users/pomek/Projects/ckeditor/ckeditor5/build/.manual-tests'
[Webpack] Starting scripts compilation...
...
...
...
Processing '/Users/pomek/Projects/ckeditor/ckeditor5/tests/manual/article'...
Finished writing '/Users/pomek/Projects/ckeditor/ckeditor5/build/.manual-tests/ckeditor5/tests/manual/article.html'
Processing '/Users/pomek/Projects/ckeditor/ckeditor5/tests/manual/mathtype'...
Finished writing '/Users/pomek/Projects/ckeditor/ckeditor5/build/.manual-tests/ckeditor5/tests/manual/mathtype.html'
Processing '/Users/pomek/Projects/ckeditor/ckeditor5/tests/manual/wproofreader'...
Finished writing '/Users/pomek/Projects/ckeditor/ckeditor5/build/.manual-tests/ckeditor5/tests/manual/wproofreader.html'
```

**Comment by jodator** [comment]
They are not:

![Screenshot_2019-09-20 Manual Test](https://user-images.githubusercontent.com/247363/65322474-40852600-dba7-11e9-97d1-c1e638b59246.png)

**Comment by jodator** [comment]
![Selection_035](https://user-images.githubusercontent.com/247363/65322671-c5703f80-dba7-11e9-8bee-fd27c326b07b.png)

[tmp.txt](https://github.com/ckeditor/ckeditor5-dev/files/3635589/tmp.txt)

**Comment by jodator** [comment]
So it might be related to the #561.

**Comment by jodator** [comment]
ps: I've added `pwd` and `pwd -P` commands outputs:
![Selection_036](https://user-images.githubusercontent.com/247363/65323084-bfc72980-dba8-11e9-9b08-171aa04028e3.png)

**Comment by pomek** [comment]
Changes weren't published yet. Did you try to use dev version of ckeditor5-dev?

**Comment by jodator** [comment]
@pomek no, just the current things that gets installed after `yarn`. I thought that it was released :thinking:

**Comment by mlewand** [comment]
I don't see this issue anymore (tested both on Win10 and Ubuntu host). @pomek @Mgsy can one of you verify that it is no longer a thing and close this issue in such case?

**Comment by pomek** [comment]
As [I mentioned in the past](https://github.com/ckeditor/ckeditor5-dev/issues/562#issuecomment-533506886), I wasn't able to reproduce the issue on my PC. We need a confirmation from @jodator.

**Comment by jodator** [comment]
I can see them now.
