### ISSUE TITLE
Error on Chrome@43

### ISSUE THREAD

**Issue by xty1992a** [ckeditor/ckeditor5-dev#565]
use  script tag inject this module on Chrome 43 got an error like this:
```
Uncaught SyntaxError: Unexpected token )
```
unfortunately, I can`t find the error in devtool (the brower version is to low).
but I think maybe the build config cause this error.

ps. sorroy for my poor English😂

**Comment by Mgsy** [comment]
Hello, Chrome 43 is a really old browser and it won't be compatible with CKEditor 5 because it doesn't support modern JavaScript. If you'd like to use CKEditor 5, please update to the latest stable version. I'd recommend it to you anyway because using such old software is a serious security issue.

**Comment by xty1992a** [comment]
well, thank for reply.

we have a software built by chromium@43, so in this case I can`t change the browser version .
I used tinyMce now.

**Comment by IgorKurkov** [comment]
Hi! Have a similar problem:) could it be solved in ckeditor 4?

**Comment by IgorKurkov** [comment]
Generally if you don't support semi-old browsers or btw mobile browsers (I receive this error on mobile chrome) so it's conversion killer for ckeditor.

**Comment by mlewand** [comment]
@IgorKurkov it's a really ancient browser and most importantly a real security issue for your end users.
I'd really put the effort on catching up with modern browser version.

**Comment by ma2ciek** [comment]
> Hi! Have a similar problem:) could it be solved in ckeditor 4?

Note that this is an issue tracker for CKEditor 5 dev tools

CKEditor 5's issue tracker is available here: [https://github.com/ckeditor/ckeditor5/issues](https://github.com/ckeditor/ckeditor5/issues)

And CKEditor 4's issue tracker is available here: [https://github.com/ckeditor/ckeditor4/issues](https://github.com/ckeditor/ckeditor4/issues)

**Comment by IgorKurkov** [comment]
Of course, its a reason to tell customers that "you are fools using old phones, please buy new", but btw 43 chrome is not ancient (android 5, 6), and it equal to safari 10, also it release date is 2015. Windows 7 release date is 2009, and as we know a lot of people use it. Is windows 7 ancient? Its no matter, users using it. We as developers need to handle these cases, this is my message. So what is the reason say that any software which you don't care to support are ancient except latest versions? I spent some time to install your product, figure out with configs, docs, custom builds, but I wasted my time, because you support only latest versions of browsers. As @xty1992a I will switch to another lib. Sorry but its reality

**Comment by ma2ciek** [comment]
@IgorKurkov, there's always an option to transpile the source code written in the ES6+ syntax down to ES5 with Babel or similar tools, which is explained in our [Building to ES5 target](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target) guide. With the proposed changes in the webpack configuration you should be able to run the code on older browsers.

> Of course, its a reason to tell customers that "you are fools using old phones, please buy new", but btw 43 chrome is not ancient (android 5, 6), and it equal to safari 10, also it release date is 2015. Windows 7 release date is 2009, and as we know a lot of people use it. Is windows 7 ancient? Its no matter, users using it.

It's very hard to create software that at the same time is compatible with old browsers and at the same is attractive for open source users to contribute and don't increase the technical debt. It's also very hard to be compatible with everything available on the market (especially in case of JS).

> We as developers need to handle these cases, this is my message. So what is the reason say that any software which you don't care to support are ancient except latest versions? I spent some time to install your product, figure out with configs, docs, custom builds, but I wasted my time, because you support only latest versions of browsers.

Like I said, in case of JS there's always (or almost always) an option to transpile code down to older syntax.

TBH we also have the [Browser compatibility section](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/browser-compatibility.html) which states which browser versions are supported and tested each day via our continuous integration tools and developers.
