### ISSUE TITLE
Remove webpack workaround for missing MathType icons

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-dev#572]
## Provide a description of the task

As a workaround to https://github.com/ckeditor/ckeditor5/issues/2043 we added some extra loader magic to our docs webpack configuration.

The upstream issue is now fixed and we no longer use this code.

## 📃 Other details

* CKEditor version: 15.0.0

**Comment by pomek** [comment]
TBH I didn't find anything related to loading images in our webpack configurations in this repository.

I guess, the ticket is about this part of the code (https://github.com/ckeditor/ckeditor5/blob/e15bf8dfbcd54cd5e47fc6b36e23be1adbeba8e0/scripts/docs/snippetadapter.js#L369-L386).
