### ISSUE TITLE
Webpack-Plugin release is not in sync with ckeditor5-util release

### ISSUE THREAD

**Issue by alfredriesen** [ckeditor/ckeditor5-dev#625]
ckeditor5-util/translations-service.js is not compatible with MultiLanguage Translations genarated by ckeditor-webpack-plugin yet.

I'm not able to make a build with MultiLanguage support. All Editor-UI remains only in English.

**Comment by Mgsy** [comment]
@ma2ciek, can you take a look at it?

**Comment by ma2ciek** [comment]
Probably you've just updated the `ckeditor5-webpack-plugin` to version 9.0. It contains breaking changes and it will work only with CKEditor5 starting from version 18, which will be released this week. Please, downgrade it for a moment to the 8.x.

**Comment by ma2ciek** [comment]
I'm sorry if it wasn't mentioned in the docs.

**Comment by ma2ciek** [comment]
PS. The webpack plugin should work now with the newest CKEditor5 packages.
