### ISSUE TITLE
Cannot start automated tests server at different port.

### ISSUE THREAD

**Issue by tomalec** [ckeditor/ckeditor5-dev#637]
Sometimes, I'd like to start the automated tests server at a port that is different than `9876`

to run a test for multiple branches/clones,
the port is occupied by another server/same server than hanged/didn't release the port.

**Comment by pomek** [comment]
Karma prevents such situation out-of-the-box. If the port isn't available, Karma will look for another one.

First terminal:

![image](https://user-images.githubusercontent.com/2270764/81931568-9dc46080-95ea-11ea-9c05-a5113f7eddd9.png)

Second terminal:

![image](https://user-images.githubusercontent.com/2270764/81931597-a5840500-95ea-11ea-8667-6fbcc6a28eb0.png)

However, the ticket itself is valid.

Unfortunately,

> to run a test for multiple branches/clones,

It won't work. Every spawn of `yarn test` creates an entry point (a file) for Karma: `/ckeditor/ckeditor5/build/.automated-tests/entry-point.js`

All processes will write to the file. We could add a port to the file name and everything should work.

**Comment by tomalec** [comment]
Then it's only for:

> the port is occupied by the server than hanged.



Steps to reproduce for me are:
1. `yarn run test --server`,
2. <kbd>Ctrl + C</kbd>,
3. wait for the server to close,
4. `yarn run test --server`,
5. `http://localhost:9876/` does not respond.

![image](https://user-images.githubusercontent.com/17435/81932432-17a91980-95ec-11ea-8a48-7a2ed1b0e1d6.png)

**Comment by tomalec** [comment]
And at least to run test server for every close of the repo.

**Comment by tomalec** [comment]
PRs are ready at https://github.com/ckeditor/ckeditor5/pull/6818, https://github.com/ckeditor/ckeditor5-dev/pull/638
