### ISSUE TITLE
dev-env: Any way to include also the additional information in the changelog?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#72]
If you create a commit like:

```
Author: ...
Date:   Fri Feb 3 16:31:58 2017 +0100

    Feature: Introduced foo. Closes: #1. Closes: #2.

    This is some additional desc.

    * With sub list.
    * And some more.
```

It'd be great if the additional description could be included in the changelog. Ofc, this is pretty complicated because we must care about markdown formatting.

**Comment by Reinmar** [comment]
This would be the proper formatting:

```
### Features

* Introduced foo. Closes: [#1](https://github.com/Reinmar/ckeditor5/issues/1). Closes: [#2](https://github.com/Reinmar/ckeditor5/issues/2). ([06e947b](https://github.com/Reinmar/ckeditor5/commit/06e947b))

  This is some additional desc.

  * With sub list.
  * And some more.
* Next point...
```

**Comment by pomek** [comment]
I resolved this ticket - https://github.com/ckeditor/ckeditor5-dev/compare/t/64...t/72, but it requires #75. So, I will wait with creating a PR.

**Comment by pomek** [comment]
I'll try to create tests for the templates. It allows checking the changes without generating the whole changelog every time.
