### ISSUE TITLE
Use deps hoisting to speed up installation time on CI

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#79]
Just like in ckeditor5, let's use hoisting (I mean Lerna's feature). This speeds up installation time from ~6 to 3:30min.

**Comment by pomek** [comment]
Reopen because https://github.com/ckeditor/ckeditor5-dev/pull/108#issuecomment-284774918.

**Comment by Reinmar** [comment]
#109 didn't work because we use too old version of Lerna ;> It needs to be bumped in the created lerna.json and here: https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-tests/bin/install-dependencies.sh#L3.

**Comment by Reinmar** [comment]
Yep, success. The time dropped from 6m30s to 4m22s: https://travis-ci.org/ckeditor/ckeditor5-image/builds/209140970.
