### ISSUE TITLE
Rethink "release main package" task

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#85]
In #64 we worked on releasing dependencies. Now we also need to think how the task to release the main package should work. What are the rules for bumping up the main package's version?

I think that the semantics we want to implement is that if any of the sub packages had a major release, the main package should have it too. If minor, then minor and if only patch versions were released, then the main package should be bumped by a patch too.

**Comment by Reinmar** [comment]
OK, I talked with @fredck about this and we want ckeditor5's version to reflect all changes in the framework. So, if there was any major change, the framework also gets a major release. Etc.

Also, so I don't forget this – ckeditor5's changelog should contain entries generated for the ckeditor5 package itself and a list of updated dependencies with prev+new versions and links to these releases.

**Comment by pomek** [comment]
I'm closing it as a DUP of https://github.com/ckeditor/ckeditor5-dev/issues/427. In that issue, we mentioned a new solution that was introduced with related PR.
