### ISSUE TITLE
Add CSP headers to manual tests server

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-dev#87]
Mostly described here - https://github.com/ckeditor/ckeditor5/issues/335#issuecomment-281325380.

We need to decide which CSP directives we would like to turn on.

**Comment by Reinmar** [comment]
> We need to decide which CSP directives we would like to turn on.

Would be good to use the ones commonly used by developers. Maybe @wwalc and @vokiel can propose something.

**Comment by wwalc** [comment]
For me the tested CSP rules should be as close as possible to this (the most strict setting possible, to detect whenever we add something that requires additional CSP rules):

```
default-src 'none';style-src 'nonce-xxx1' 'unsafe-inline';script-src 'nonce-xxx2';
```

and for features which will operate on images, CSP should be extended to:

```
default-src 'none';style-src 'nonce-xxx1' 'unsafe-inline';script-src 'nonce-xxx2';img-src * data:;
```
Once the issue with SVG images is resolved, we should get rid of 'unsafe-inline'.

**Comment by Reinmar** [comment]
We're discussing in https://github.com/ckeditor/ckeditor5/issues/335#issuecomment-397589047 how to resolve this ticket. The main point is that we need to extract CSS to a separate file and I'm not a big fan of doing this by default in all manual tests.

**Comment by Reinmar** [comment]
This is done already.
