### ISSUE TITLE
Disable background throttling in Chrome

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#88]
It turns out that there's a solution to that problematic behaviour if Chrome getting super slow when in bg: https://bugs.chromium.org/p/chromium/issues/detail?id=485425#c21

Let's enable it in our tests.

**Comment by pomek** [comment]
I have to reopen this issue. In fact I introduced `--disable-background-timer-throttling` option for Chrome… but it is a Chrome for CI, not for "local" Chrome.

**Comment by Reinmar** [comment]
It doesn't work for me unfortunately. But it seems that there's a bug on MacOS now: https://bugs.chromium.org/p/chromium/issues/detail?id=605498. So once it's fixed we should be fine.
