### ISSUE TITLE
Breaking changes and new feature were ignored

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev#97]
![image](https://cloud.githubusercontent.com/assets/156149/23609837/48085536-0270-11e7-814b-00daf98bf454.png)

Something is wrong here. The version bump should be minor, not patch.

The changelog section is ok:

```
## [0.7.1](https://github.com/ckeditor/ckeditor5-heading/compare/v0.7.0...v0.7.1) (2017-03-06)

### Features

* Enabled configuration and localization of available headings (see `config.heading.options`). Closes [#33](https://github.com/ckeditor/ckeditor5/issues/33). ([de07a0c](https://github.com/ckeditor/ckeditor5-heading/commit/de07a0c))

### Other changes

* Uploaded translations. ([50583b4](https://github.com/ckeditor/ckeditor5-heading/commit/50583b4))


### BREAKING CHANGES

* The `heading` command now accepts `id` option, not `formatId`.
```

**Comment by pomek** [comment]
Works fine for versions >1.0.0. 

![image](https://cloud.githubusercontent.com/assets/2270764/23611848/3ce19e20-0279-11e7-97b0-1124dfea96ca.png)

Will check with versions <1.0.0.

**Comment by pomek** [comment]
![image](https://cloud.githubusercontent.com/assets/2270764/23611914/7c81a282-0279-11e7-946b-d6861cd30d52.png)

**Comment by Reinmar** [comment]
So did you confirm the issue or not? I'm 100% sure of it. I had to manually change versions of half of packages.

**Comment by pomek** [comment]
I confirm the bug. For merge commits our commit convention starts at the second line.

![image](https://cloud.githubusercontent.com/assets/2270764/23646384/e9673afa-0310-11e7-9264-f1ff8f477ef3.png)

I fixed it [`transformCommit()`](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-env/lib/release-tools/changelog/writer-options.js#L66-L75) function which is used to generate the changelog entries. 

The same function needs to be used in [`getNewVersionType()`](https://github.com/ckeditor/ckeditor5-dev/blob/master/packages/ckeditor5-dev-env/lib/release-tools/utils/getnewreleasetype.js#L43-L64) function. 

When we will use `transformCommit()` in `getNewVersionType()`, we will be able to easly way resolve #100.

**Comment by pomek** [comment]
> When we will use transformCommit() in getNewVersionType(), we will be able to easly way resolve #100.

Unfortunately, I won't be easy. `conventional-recommended-bump` does not allow passing custom options for [`gitRawCommits`](https://github.com/conventional-changelog/conventional-recommended-bump/blob/master/index.js#L51-L54) function. 

But, this ticket is not about it.

**Comment by Reinmar** [comment]
> When we will use transformCommit() in getNewVersionType(), we will be able to easly way resolve #100.

#100 has nothing to do with this. I mean... #100 sounds super trivial – just add the `v` to the version read from package.json.

**Comment by pomek** [comment]
Ehh. I wrote #100 but I thought about #96… Sorry.
